### PR TITLE
add options page and setting for randomization

### PR DESCRIPTION
**Pull request by slhck**
This allows disabling randomization to make the UI more consistent for users who like it.

### CODE REVIEW

**Comment by slhck** [comment]
I chose to send this PR over the one with the alert since that is another feature I wanted implemented.

The default setting is of course the behavior of the extension as it was before.

**Comment by slhck** [comment]
Any feedback on this PR?

**Comment by AvnerCohen** [comment]
@slhck Haven't gotten to it yet, apologies.
Will review and reply next week.

In general though, I totally agree this could be a nice feature, I too am not sure the randomization makes it easier or harder to detect the diff scenarios.

**Comment by slhck** [comment]
Thanks!

In my personal use case, I would like consistency. Seeing the same emoji makes it predictable for me to know what kind of email is being sent. I still very much observe the warning and alert signs and think twice before sending.
Seeing a random emoji always made me have to think … well, another time.
Giving the user the choice to disable it (while keeping the default) would make sense here.

**Comment by AvnerCohen** [comment]
@slhck Went over it, it looks great.
Would you please also add a section to the readme with a screenshot of the option and short description of the diff between random and not random?

Also, in retro spect I prefer the non randmoized version, so I will publish this as a major version, but please set the default to be non-randomized. I understand this will be a breaking change, but there is really no harm in it.

Thanks for the effort on this !

**Comment by slhck** [comment]
I updated the branch. The options now explain what it does:

image

I hope that's all fine for you.

**Comment by slhck** [comment]
Just out of curiosity, did you change the name of the branch from master to main? Or was it done automatically?

**Comment by AvnerCohen** [comment]
I did't change anything, This is the new github default - https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

The repo was created at a later date, so these announcement already took effect.

**Comment by slhck** [comment]
Thanks. I'm just trying to verify an issue with my own repo.

Glad to see the PR merged!

**Pull request merged**
