### PR TITLE
WIP: add options page

### PR DESCRIPTION
**Pull request by slhck**
This is a work in progress for you to check how to add options.

The only thing missing is actually querying the "warn" setting from the injected content script. This seems to be a bit tricky.

Let me know if you want to continue working on this or whether I should try.

### CODE REVIEW

**Comment by slhck** [comment]
Updated the code so the options are available in `content.js`.

**Comment by AvnerCohen** [comment]
@slhck Thanks for the effort on this! really appriciated.

I spent a bit of time looking at the high level design here, and I suspect that this is actually not possible:
https://github.com/KartikTalwar/gmail.js/issues/550


wdyt ?

**Comment by slhck** [comment]
Oh, didn't expect that to be so complicated. That's too bad! So there's no way to detect that button being clicked and stopping the event?

**Comment by AvnerCohen** [comment]
At the very least, it seems like there is no safe solution to do that using the existing button.
Maybe an alternative approach would be to hijack the original button and replace it.

I am just not 100% sure about the extra complexity.

At any case, I think moving forward, it's best to spend any time on solving this challenge first as this is the main obstacle.

**Comment by slhck** [comment]
Closing this for now until we find a solution (the other PR #5) allows setting options, so we can go from there.

**Pull request closed without merging**
